### ISSUE TITLE
One-hot encoding of sequences

### ISSUE THREAD

**Issue by cossio** [BioJulia/BioSequences.jl#130]
This is a feature request.

Machine learning models of biological sequences often work by representing sequences in one-hot encoding. I think it would be nice to add support for onehot encoding/decoding of biological sequences in this package.

**Comment by jakobnissen** [comment]
Hello @cossio 

I think that's outside the scope of BioSequences. One-hot encoding pertains to the specific machine learning model that uses DNA sequences, not to the sequences themselves. There is no way we can predict what kind of embedding or transformation machine learning people will want to do with biological sequences, so that is better left up to the people who want to do that. For example - should it include Ns, or other ambiguous nucleotides, should it be a bitmatrix or an integer matrix, and should amino acids use a reduced alphabet?

**Comment by cossio** [comment]
@jakobnissen I see your point. Maybe there are some dedicated packages for this purpose out there?

**Comment by jakobnissen** [comment]
I'm not aware of any Julia package using machine learning on biological sequences. But it's fairly easy to add a function that one-hot encodes sequences. Here's one:
`onehot(s::BioSequence{A}) where A = reduce(vcat, [reshape(a .== i, 1, :) for i in A()])`
Not the most efficient, but probably good enough for most use cases.
