### ISSUE TITLE
Make FASTA and FASTQ readers / writers compatible with FileIO

### ISSUE THREAD

**Issue by BenJWard** [BioJulia/BioSequences.jl#39]
We've already done great work for making reading formatted bioinformatics generic and simple to understand, it is a good idea to make what we have compatible with FileIO so for users then, opening and reading files like FASTA and FASTQ the same as if they were working with a CSV file.

**Comment by Zymergen-phaverty** [comment]
This would mean that reading from gzipped FASTQ files could work, correct?

**Comment by BenJWard** [comment]
Does it not work with FASTX and TranscodingStreams already?

**Comment by Zymergen-phaverty** [comment]
Cool. I didn't know about TranscodingStreams. This reveals a bug in FASTX.jl, however:

I did `reader = FASTQ.Reader(GzipDecompressorStream(open(fastq)))` , which I think is what you meant. I get `UndefVarError: stream not defined`. The bug is visible in the relevant code (below). I'll post an issue over on FASTX.jl.

"""
function Reader(input::IO; fill_ambiguous = nothing)
    if fill_ambiguous === nothing
        seq_transform = nothing
    else
        seq_transform = generate_fill_ambiguous(fill_ambiguous)
    end
    if !(input isa TranscodingStream)
        stream = TranscodingStreams.NoopStream(input)
    end
    return Reader(State(stream, 1, 1, false), seq_transform)
end
"""

**Comment by phaverty** [comment]
This FASTX bug appears to be fixed in master. And, the TranscodingStreams trick works like a charm! It would be great to have an example of this in the docs for BioSequences and/or FASTX. FASTQ files seem to always be gzipped in my experience.
